trigger: "hz(1, day)"
end: now
system: db
format:
  table: authors
schema:
  type: object
  properties:
    id:
      type: number
      minimum: 1
      scale: 0
      step: 1
    name:
      type: name
    email:
      type: email
    bio:
      type: lorem.sentence
    created_at:
      type: context
      path: ["clock", "now"]
